export const MAXPARA = 100;
export const MAXACTION = 5;
export const MAXREMAINTIME = 5;
export const MAXPET = 5;
export const LOWERBOUND = -10;
export const DIFFSTATUS = 1;
export const DIFFSKILL = 2;
export const DIFFEXP = 1;
export const TIME = 1000; // milliseconds
export const ISREQUIRED = true;
export const MINDATE = "1920-01-01";
export const MAXDATE = "2020-01-01";
